---

stages:
  - build
  - test

build:
  stage: build
  tags:
    - linux
  script:
    - docker build -t test:updateawskeys .

test:
  stage: test
  tags:
    - linux
  script:
    - alias aws='echo aws'
    - DO_DEFAULT=rubbish sh updateawskeys.sh||echo "Test 1 worked"
    - DO_DEFAULT=TRUE DO_SECTION=rubbish sh updateawskeys.sh||echo "Test 2 worked"
